### ISSUE TITLE
Invalid_Argument!!!

### ISSUE THREAD

**Issue by Ghafooor** [zhiru/laravel-moodle#1]
Hello!
I have this message when I install this package :
[InvalidArgumentException]

  Could not find a version of package zhiru/laravel-moodle matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.
what is problem ? and how i can solve it !!!
i need answer quickly, please...

**Comment by zhiru** [comment]
Sorry, i was not maintaining this package and i see just now!

This was my first package try, but if you need yet i'll try to help!

**Comment by zhiru** [comment]
try to put this on your composer.json
"minimum-stability": "dev"
